/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkersIndexRouteImport } from './routes/workers/index'
import { Route as SchedulersIndexRouteImport } from './routes/schedulers/index'
import { Route as JobsIndexRouteImport } from './routes/jobs/index'
import { Route as FlowsIndexRouteImport } from './routes/flows/index'
import { Route as QueuesQueueNameRouteImport } from './routes/queues/$queueName'
import { Route as JobsJobIdRouteImport } from './routes/jobs/$jobId'
import { Route as FlowsFlowIdRouteImport } from './routes/flows/$flowId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkersIndexRoute = WorkersIndexRouteImport.update({
  id: '/workers/',
  path: '/workers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulersIndexRoute = SchedulersIndexRouteImport.update({
  id: '/schedulers/',
  path: '/schedulers/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsIndexRoute = FlowsIndexRouteImport.update({
  id: '/flows/',
  path: '/flows/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueuesQueueNameRoute = QueuesQueueNameRouteImport.update({
  id: '/queues/$queueName',
  path: '/queues/$queueName',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowsFlowIdRoute = FlowsFlowIdRouteImport.update({
  id: '/flows/$flowId',
  path: '/flows/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/queues/$queueName': typeof QueuesQueueNameRoute
  '/flows/': typeof FlowsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/schedulers/': typeof SchedulersIndexRoute
  '/workers/': typeof WorkersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/queues/$queueName': typeof QueuesQueueNameRoute
  '/flows': typeof FlowsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/schedulers': typeof SchedulersIndexRoute
  '/workers': typeof WorkersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/flows/$flowId': typeof FlowsFlowIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/queues/$queueName': typeof QueuesQueueNameRoute
  '/flows/': typeof FlowsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/schedulers/': typeof SchedulersIndexRoute
  '/workers/': typeof WorkersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/flows/$flowId'
    | '/jobs/$jobId'
    | '/queues/$queueName'
    | '/flows/'
    | '/jobs/'
    | '/schedulers/'
    | '/workers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/flows/$flowId'
    | '/jobs/$jobId'
    | '/queues/$queueName'
    | '/flows'
    | '/jobs'
    | '/schedulers'
    | '/workers'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/flows/$flowId'
    | '/jobs/$jobId'
    | '/queues/$queueName'
    | '/flows/'
    | '/jobs/'
    | '/schedulers/'
    | '/workers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  FlowsFlowIdRoute: typeof FlowsFlowIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  QueuesQueueNameRoute: typeof QueuesQueueNameRoute
  FlowsIndexRoute: typeof FlowsIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
  SchedulersIndexRoute: typeof SchedulersIndexRoute
  WorkersIndexRoute: typeof WorkersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workers/': {
      id: '/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof WorkersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedulers/': {
      id: '/schedulers/'
      path: '/schedulers'
      fullPath: '/schedulers/'
      preLoaderRoute: typeof SchedulersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/': {
      id: '/flows/'
      path: '/flows'
      fullPath: '/flows/'
      preLoaderRoute: typeof FlowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queues/$queueName': {
      id: '/queues/$queueName'
      path: '/queues/$queueName'
      fullPath: '/queues/$queueName'
      preLoaderRoute: typeof QueuesQueueNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flows/$flowId': {
      id: '/flows/$flowId'
      path: '/flows/$flowId'
      fullPath: '/flows/$flowId'
      preLoaderRoute: typeof FlowsFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  FlowsFlowIdRoute: FlowsFlowIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  QueuesQueueNameRoute: QueuesQueueNameRoute,
  FlowsIndexRoute: FlowsIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
  SchedulersIndexRoute: SchedulersIndexRoute,
  WorkersIndexRoute: WorkersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
